/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Deepika
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.*;


public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pcode", "Price", "Quantity", "Name"
            }
        ));
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 420, 100);

        jButton1.setText("Display Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 250, 150, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Grand Total");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(233, 261, 71, 17);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(318, 258, 76, 30);

        jButton2.setText("Delete Selected Product");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 290, 147, 23);

        jButton3.setText("Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 330, 150, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(547, 0, 0, 0);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("My Orders");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 70, 140, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 20, 360, 50);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Deepika\\OneDrive - vit.ac.in\\Desktop\\IP Project\\Bigbasket-logo.jpg")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 30, 200, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Deepika\\OneDrive - vit.ac.in\\Desktop\\IP Project\\background.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -6, 880, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m=(DefaultTableModel)ta1.getModel();
           
        double gt=0.0;
        
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
            
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","deepika");
            
          Statement stmt=con.createStatement();
          
          String qr="select * from cart";
          
          ResultSet rs=stmt.executeQuery(qr);
          
          while(rs.next())
          {
              
             int pcode=rs.getInt("pcode");
             double price=rs.getDouble("price");
             double q=rs.getDouble("q");
             String name=rs.getString("name");
             gt+=q*price;
              m.addRow(new Object[]{pcode,price,q,name});
              
                            
          }
          con.close();
          stmt.close();
          rs.close();
        }
        catch(Exception e)
        {            
                System.out.println(e.getMessage());                
        }
        
        t1.setText(gt+"");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m=(DefaultTableModel)ta1.getModel();
        int row=ta1.getSelectedRow();
        String cell=(ta1.getModel().getValueAt(row,3).toString());
        String q="delete from cart where name='"+cell+"'";
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","deepika");
            
          Statement stmt=con.createStatement();
          
          stmt.executeUpdate(q);
        }       
        catch(Exception e)
        {           
         System.out.println(e.getMessage());
        }
         m.removeRow(row);  
         
         
         
        double gt=0.0;
        
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
            
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","deepika");
            
          Statement stmt=con.createStatement();
          
          String qr="select * from cart";
          
          ResultSet rs=stmt.executeQuery(qr);
          
          while(rs.next())
          {
              
             int pcode=rs.getInt("pcode");
             double price=rs.getDouble("price");
             double qt=rs.getDouble("q");
             String name=rs.getString("name");
             gt+=qt*price;
                         
                            
          }
          con.close();
          stmt.close();
          rs.close();
        }
        catch(Exception e)
        {            
                System.out.println(e.getMessage());                
        }
        
        t1.setText(gt+"");       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m=(DefaultTableModel)ta1.getModel();
        
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
            
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","deepika");
            
          Statement stmt=con.createStatement();
          
          String qr="Delete from cart";
          
           stmt.executeUpdate(qr);   
                  
          con.close();
          stmt.close();
         
        }
        catch(Exception e)
        {            
                System.out.println(e.getMessage());                
        }
        
       JOptionPane.showMessageDialog(null, "Your order has been successfully placed."+"\n"+"Thank You");
       Home a = new Home ();
        a.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Home a = new Home ();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTable ta1;
    // End of variables declaration//GEN-END:variables
}
