
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Deepika
 */
public class Dal extends javax.swing.JFrame {

    /**
     * Creates new form Dal
     */
    public Dal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        l1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Channa Kabuli", "Rajma", "Toor Dal", "Moong Dal", "Masoor Dal", "Udid Dal", "Channa Dal" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(l1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 100, 154);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pcode");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 60, 38, 17);

        t4.setColumns(20);
        t4.setRows(5);
        jScrollPane2.setViewportView(t4);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 270, 544, 81);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 100, 35, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 140, 29, 17);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(240, 60, 140, 30);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(240, 100, 140, 30);
        getContentPane().add(t3);
        t3.setBounds(240, 140, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Benefits");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 240, 47, 17);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(152, 174, 33, 0);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Deepika\\OneDrive - vit.ac.in\\Desktop\\IP Project\\Bigbasket-logo.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 1, 200, 50);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Deepika\\OneDrive - vit.ac.in\\Desktop\\IP Project\\istockphoto-639201180-612x612.jpg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 210, 50, 39);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 180, 70, 17);
        getContentPane().add(t6);
        t6.setBounds(240, 180, 140, 30);

        jButton4.setText("Show my Cart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(460, 230, 110, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Deepika\\OneDrive - vit.ac.in\\Desktop\\IP Project\\background.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 930, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel m=new DefaultListModel();
        l1.setModel(m);
        
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
            
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","deepika");
            
          Statement stmt=con.createStatement();
                   
          String st=(String)l1.getSelectedValue();
          
          String qr="select * from Dal";
          
          ResultSet rs=stmt.executeQuery(qr);
          
          while(rs.next())
          {
              
             String name=rs.getString("name");
              m.addElement(name);
          }
          con.close();
          stmt.close();
          rs.close();
        }
        catch(Exception e)
        {            
                System.out.println(e.getMessage());                
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        // TODO add your handling code here:
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
            
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","deepika");
            
          Statement stmt=con.createStatement();
                   
          String st=(String)l1.getSelectedValue();
          
          String qr="select * from dal where name = '"+st+"';";
          
          ResultSet rs=stmt.executeQuery(qr);
          
          while(rs.next())
          {
              int pcode=rs.getInt("pcode");
              String name=rs.getString("name");
              double price=rs.getDouble("price");
              String benefits=rs.getString("benefits");
              t1.setText(""+pcode);
              t2.setText(""+name);
              t3.setText(""+price);
              t4.append(""+benefits);
          }
          con.close();
          stmt.close();
          rs.close();
        }
        catch(Exception e)
        {            
                System.out.println(e.getMessage());                
        }   
    }//GEN-LAST:event_l1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home a = new Home ();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String pcode=t1.getText();
          
          String price=t3.getText();
          
          String q=t6.getText();
          
          String name=t2.getText();
        
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
            
          Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/IP_Project","root","deepika");
            
          Statement stmt=con.createStatement();
                   
          
          
          String qr = "Insert into Cart values('"+pcode+"','"+price+"','"+q+"','"+name+"');";
          
          stmt.executeUpdate(qr);
          
          con.close();
          stmt.close();
          
          
         }
        
        
         catch(Exception e)
        {            
                System.out.println(e.getMessage());                
        }// TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Cart a = new Cart ();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList l1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextArea t4;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
